import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'tertiary-fixed': '#ffdbcb',
        'on-primary-fixed-variant': '#004493',
        'surface-container-lowest': '#ffffff',
        'outline': '#727785',
        'error': '#ba1a1a',
        'on-primary': '#ffffff',
        'primary-container': '#1a73e8',
        'outline-variant': '#c1c6d6',
        'tertiary-container': '#c55500',
        'on-tertiary-fixed-variant': '#783100',
        'surface-dim': '#d7dae0',
        'surface-variant': '#dfe3e8',
        'on-secondary': '#ffffff',
        'secondary-fixed': '#89fa9b',
        'on-error-container': '#93000a',
        'tertiary': '#9e4300',
        'on-surface-variant': '#414754',
        'surface-tint': '#005bc0',
        'secondary-fixed-dim': '#6ddd81',
        'surface-container-high': '#e5e8ee',
        'on-surface': '#181c20',
        'on-primary-fixed': '#001a41',
        'primary': '#005bbf',
        'tertiary-fixed-dim': '#ffb691',
        'error-container': '#ffdad6',
        'secondary-container': '#86f898',
        'inverse-on-surface': '#eef1f7',
        'on-secondary-fixed-variant': '#005320',
        'inverse-primary': '#adc7ff',
        'background': '#f7f9ff',
        'on-secondary-fixed': '#002108',
        'surface-container-low': '#f1f4fa',
        'on-background': '#181c20',
        'surface-bright': '#f7f9ff',
        'on-primary-container': '#ffffff',
        'surface-container-highest': '#dfe3e8',
        'on-tertiary': '#ffffff',
        'primary-fixed-dim': '#adc7ff',
        'secondary': '#006e2c',
        'surface-container': '#ebeef4',
        'inverse-surface': '#2d3135',
        'on-secondary-container': '#00722f',
        'surface': '#f7f9ff',
        'on-tertiary-container': '#0e0200',
        'primary-fixed': '#d8e2ff',
        'on-tertiary-fixed': '#341100',
        'on-error': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'md': '1.5rem',
        'xs': '0.5rem',
        'sm': '1rem',
        'lg': '2.5rem',
        'xl': '4rem',
        'gutter': '24px',
        'base': '4px',
        'container-max': '1280px',
      },
      fontFamily: {
        'display-lg': ['Manrope', 'sans-serif'],
        'headline-lg': ['Manrope', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'headline-md': ['Manrope', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'label-sm': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
      },
      maxWidth: {
        'container-max': '1280px',
      },
    },
  },
  plugins: [],
}

export default config
